### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by Caavv** [cooldogedev/BedrockEconomy#102]
Hi, I´m writing this because when I put the plugin in my server, the cpu rises to drastic levels. After a long search i realised that
i don´t know where the mistake came from xD. The only I know is that the thing that do rises the cpu is this plugin. And I would like to know why. If they could help me I would be very happy, thanks. :D

*Important Thing*
I just have 250% of cpu and whith this problem my cpu rised to 210-220% of cpu

**Comment by cooldogedev** [comment]
Can you send me the server's timings

**Comment by Caavv** [comment]
The timings are the things that you have that show the cpu, memory etc?

**Comment by cooldogedev** [comment]
It's a PMMP command, /timings start then after a while of trying BedrockEconomy commands you run /timings paste, It'll generate a link. I want you to send the link here

**Comment by Caavv** [comment]
https://timings.pmmp.io/?id=309813

**Comment by cooldogedev** [comment]
> This report is very short. It may not be representative of your server's actual performance.

In any case, the report looks fine, BedrockEconomy isn't affecting anything.

**Comment by PerzivalFr** [comment]
Good morning,

Being myself a game server host for Minecraft pocket edition, I have 15 clients who use your plugins..

Your plugin eats all the cpu of my servers..

In the config you put 2 basic thead since I use the pterodactyle panel it takes 200% constant cpu all the time with only this problematic plugin ....


Do something to fix this problem because it's getting boring, I'm on the verge of saying not to recommend your plugin because it does shit on the servers of my clients who only have 2 hearts on their mcpe offers..

If you want, I'll give you an offer and test you yourself, you'll understand the mess it's made...


Ps: I have never seen a plugin that consumes so much since I made mcpe servers or even that I hosted..


You can contact me by discord: perzival

Thanks
Maxime CEO of winheberg
https://winheberg.fr/?lang=en

**Comment by PerzivalFr** [comment]
I think we should work on a solution that could already stop using the cpu for nothing at all..

Even EconomyApi has never consumed cpu like that!

**Comment by Caavv** [comment]
You see? That´s problem is very annoying and I'm not the only one who suffers from it, I think that they should to find a solution

**Comment by Caavv** [comment]
And I don´t seek to offend, but when I remove the plugin, my cpu is in 10%. But when I put the plugin again, my cpu rises to 200%, I just want a solution for me and for others owners that they don't know how to fix it

**Comment by PerzivalFr** [comment]
Yes it's on it's a big problem because when you are a host and you have more than 130 pocketmine servers running and you only have 30 with this buggy bedrock economy plugin here's what makes me load cpu on my dedicate which should not be there...

In addition I have already seen 15 tickets for this abusive cpu overload plugin which was made only with this plugin....


If nothing has been done, I will not recommend the plugin to my clients to protect their servers and also my infrastructure..

**Comment by Caavv** [comment]
Yes bro.. But idk

**Comment by cooldogedev** [comment]
Looks like this issue might be related to [libSQL](https://github.com/cooldogepm/libSQL), however this doesn't mean that this is valid. I need more information and timings that have a duration of 5-10 minutes at least.

**Comment by Caavv** [comment]
But could you at least look for a solution to the problem? I'm telling you seriously, my cpu doesn't go below 210%, I beg you, at least check and look for possible solutions, pls.

**Comment by NotEnriko** [comment]
> Looks like this issue might be related to [libSQL](https://github.com/cooldogepm/libSQL), however this doesn't mean that this is valid. I need more information and timings that have a duration of 5-10 minutes at least.

i have 7 minute timings of server running bedrock economy version 2.1.2 with pocketmine v5.4.2
https://timings.pmmp.io/?id=310243

**Comment by cooldogedev** [comment]
> > Looks like this issue might be related to [libSQL](https://github.com/cooldogepm/libSQL), however this doesn't mean that this is valid. I need more information and timings that have a duration of 5-10 minutes at least.
> 
> i have 7 minute timings of server running bedrock economy version 2.1.2 with pocketmine v5.4.2 https://timings.pmmp.io/?id=310243

Timings look fine, perhaps it's an issue with dedicated hosting providers.

**Comment by NotEnriko** [comment]
now i know the problem
if you look inside the config.yml
on the line 18 (database threads) it was the main problem
if you keep the default setting for database threads on the config.yml (2)
then it will use 200% of your cpu 
but after i changed it into 1
the cpu usage are mostly from 100% to 115%
so this could be the problem

**Comment by cooldogedev** [comment]
> now i know the problem if you look inside the config.yml on the line 18 (database threads) it was the main problem if you keep the default setting for database threads on the config.yml (2) then it will use 200% of your cpu but after i changed it into 1 the cpu usage are mostly from 100% to 115% so this could be the problem

Then it means the host you're using isn't assigning you enough resources, therefore starting a thread takes 100% of your CPU

**Comment by cooldogedev** [comment]
Either use a VPS or find a new provider that assigns enough resources

**Comment by PerzivalFr** [comment]
> > maintenant je connais le problème si vous regardez à l'intérieur du config.yml sur la ligne 18 (threads de base de données), c'était le problème principal si vous conservez le paramètre par défaut pour les threads de base de données sur le config.yml (2), alors il utilisera 200% de votre processeur mais après l'avoir changé en 1, l'utilisation du processeur est principalement comprise entre 100 % et 115 %, cela pourrait donc être le problème
> 
> Cela signifie alors que l'hôte que vous utilisez ne vous alloue pas suffisamment de ressources, donc le démarrage d'un thread prend 100 % de votre CPU

It's your plugin that is badly done...


I am a host myself, your plugin consumes too much for nothing and I repeat it EconomyApi has never had this problem so instead of blaming the host directly, look for yourself because saying switching to a vps will not solve the problem. your plugin will use 2 Thread all the time....

**Comment by PerzivalFr** [comment]
Here are 2 tries of your plugin on a VPS and a game server and the result and the same..


https://zupimages.net/viewer.php?id=23/34/draq.png

https://zupimages.net/viewer.php?id=23/34/aovy.png


It's not by telling the person to take something more powerful that you will solve the problem...

Your plugin has an internal problem that makes it consume too much for a pocketmine plugin and the worst part is that it consumes 2 threads all the time.. and it shouldn't consume that much, no interest..

**Comment by cooldogedev** [comment]
> Here are 2 tries of your plugin on a VPS and a game server and the result and the same..
> 
> https://zupimages.net/viewer.php?id=23/34/draq.png
> 
> https://zupimages.net/viewer.php?id=23/34/aovy.png
> 
> It's not by telling the person to take something more powerful that you will solve the problem...
> 
> Your plugin has an internal problem that makes it consume too much for a pocketmine plugin and the worst part is that it consumes 2 threads all the time.. and it shouldn't consume that much, no interest..

The plugin is multi-threaded, it executes queries on a different thread. You're not providing enough resources to the users therefore causing their CPU usage to jump to 100%.

**Comment by cooldogedev** [comment]
EconomyAPI executes queries in the main thread, you can achieve the 100% usage with it by running its commands repeatedly which also causes the server to freeze.

**Comment by cooldogedev** [comment]
> your plugin will use 2 Thread all the time....

It starts two threads and `waits` them until a query arrives for processing. This is all implemented in [libSQL](https://github.com/cooldogepm/libSQL)
