### ISSUE TITLE
Scorehud integration

### ISSUE THREAD

**Issue by GamerMJay** [cooldogedev/BedrockEconomy#36]
Hey, can you please create BedrockmoneyScore? for my ScoreHud 

here a example https://poggit.pmmp.io/p/EcoAPIScore/1.1.0

Would be cool if you could do something like that because the money doesn't show up in the ScoreHud

**Comment by Ifera** [comment]
Hey, just a heads up, you can integrate ScoreHud support directly within BedrockEconomy instead of having a separate plugin made. This would be much easier for the end user as well. You can look at how PiggyFactions integrated the support of ScoreHud.

**Comment by GamerMJay** [comment]
Hello, a question, how are you doing with this addon?

**Comment by cooldogedev** [comment]
use the latest release of BedrockEconomy 2.0.5 ([addon](https://github.com/cooldogedev/BedrockEconomy/blob/main/src/cooldogedev/BedrockEconomy/addon/scorehud/ScoreHudAddon.php)). Add `bedrockeconomy.balance` tag to your scorehud and it'll do it for you without the need for downloading an external extension because it is bundled with the code.

**Comment by GamerMJay** [comment]
Oh Thank you 😄
